export var PRODUCTION = process.env.PRODUCTION;
export var API_ENDPOINT = process.env.API_ENDPOINT ;
export var GALAXY_ENDPOINT = process.env.GALAXY_ENDPOINT ;
export var FAQ_ENDPOINT = process.env.FAQ_ENDPOINT ;
export var CONNECTOR_API_ENDPOINT = process.env.CONNECTOR_API_ENDPOINT ;
export var WORKFLOW_API_ENDPOINT = process.env.WORKFLOW_API_ENDPOINT ;
export var OIDC_ENDPOINT = process.env.OIDC_ENDPOINT ;
export var AAI_ENDPOINT = process.env.AAI_ENDPOINT ;
export var VIEWER_ENDPOINT = process.env.VIEWER_ENDPOINT ;